### ISSUE TITLE
Disaster Tracker

### ISSUE THREAD

**Issue by janton42** [janton42/hl_main#9]
Should:

- [ ] Find current/recent disasters
- [ ] Take in a list of people and their location
- [ ] Return a list of people in possible locations
